services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  nimbus:
    image: storm:2.6.1
    command: storm nimbus
    ports:
      - "6627:6627"
      - "8081:8080"
    environment:
      - STORM_LOCAL_HOSTNAME=nimbus
    depends_on:
      - zookeeper
      - kafka

  supervisor:
    image: storm:2.6.1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
      - kafka

  ui:
    image: storm:2.6.1
    command: storm ui
    ports:
      - "8744:8744"
    depends_on:
      - nimbus

  kafka-init:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CFG_BOOTSTRAP_SERVERS: kafka:9092
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Waiting for Kafka to be ready..."
        for i in {1..30}; do
          kafka-topics.sh --bootstrap-server kafka:9092 --list && break
          echo "Kafka not ready yet... retrying"
          sleep 2
        done
        
        # Creare topicuri
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-1-admin --partitions 1 --replication-factor 1
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-1-forward --partitions 1 --replication-factor 1
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-2-admin --partitions 1 --replication-factor 1
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-2-forward --partitions 1 --replication-factor 1
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-3-admin --partitions 1 --replication-factor 1
        kafka-topics.sh --bootstrap-server kafka:9092 --create --topic broker-3-forward --partitions 1 --replication-factor 1
        
        echo "Topics created."
